[package]
name = "macros"
description = "Macros for lib-proc-macro-util"

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
base.workspace = true
